version: "3"

vars:
  PROGRAM: websitewatcher

tasks:
  deps:
    cmds:
      - go mod tidy -v

  update:
    deps: [ generate ]
    cmds:
      - go get -u
      - go mod tidy -v

  generate:
    deps: [ sqlc ]

  sqlc:
    cmds:
      - sqlc generate

  setup:
    cmds:
      - go install github.com/pressly/goose/v3/cmd/goose@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install mvdan.cc/gofumpt@latest

  build:
    aliases: [ default ]
    deps: [ deps, generate ]
    env:
      CGO_ENABLED: 0
    cmds:
      - go fmt ./...
      - gofumpt -l -w .
      - go vet ./...
      - go build -o {{.PROGRAM}}

  test:
    deps: [ deps, generate ]
    env:
      CGO_ENABLED: 1 # required by -race
    cmds:
      - go test -race -cover ./...

  run:
    deps: [ build ]
    cmds:
      - ./{{.PROGRAM}} -debug -dry-run -config config.json

  configcheck:
    deps: [ build ]
    cmds:
      - ./{{.PROGRAM}} -config config.json -configcheck

  version:
    deps: [ build ]
    cmds:
      - ./{{.PROGRAM}} -version

  lint:
    cmds:
      - golangci-lint run ./... --timeout=30m
      - go mod tidy

  lint-update:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b {{ .GOPATH }}/bin
      - golangci-lint --version
    vars:
      GOPATH:
        sh: go env GOPATH

  tag:
    cmds:
      - git tag -a "${TAG}" -m "${TAG}"
      - git push origin "${TAG}"
    preconditions:
      - sh: '[[ -n "${TAG}" ]]'
        msg: "Please set the TAG environment variable"
