version: "3"

vars:
  PROGRAM: websitewatcher

tasks:
  deps:
    cmds:
      - go mod tidy -v

  update:
    deps: [deps, generate]
    cmds:
      - go get -u
      - go get -u tool
      - go mod tidy -v

  generate:
    deps: [sqlc, templ]

  sqlc:
    cmds:
      - go tool sqlc generate

  templ:
    cmds:
      - go tool templ generate
      - go tool templ fmt .

  build:
    aliases: [default]
    deps: [deps, generate]
    env:
      CGO_ENABLED: 0
    cmds:
      - go fmt ./...
      - go tool gofumpt -l -w .
      - go vet ./...
      - go build -o {{.PROGRAM}}

  test:
    deps: [deps, generate]
    env:
      CGO_ENABLED: 1
    cmds:
      - go test -race -cover ./...

  run:
    deps: [build]
    cmds:
      - ./{{.PROGRAM}} -debug -dump-html -dry-run -config config.json

  run-once:
    deps: [build]
    cmds:
      - ./{{.PROGRAM}} -debug -dump-html -dry-run -config config.json -mode once

  configcheck:
    deps: [build]
    cmds:
      - ./{{.PROGRAM}} -config config.json -configcheck

  version:
    deps: [build]
    cmds:
      - ./{{.PROGRAM}} -version

  lint:
    cmds:
      - golangci-lint run ./... --timeout=30m
      - go mod tidy

  lint-update:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b {{ .GOPATH }}/bin
      - golangci-lint --version
    vars:
      GOPATH:
        sh: go env GOPATH

  tag:
    cmds:
      - git tag -a "${TAG}" -m "${TAG}"
      - git push origin "${TAG}"
    preconditions:
      - sh: '[[ -n "${TAG}" ]]'
        msg: "Please set the TAG environment variable"
