// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type Watch struct {
	ID          int64
	Name        string
	Url         string
	LastFetch   time.Time
	LastContent []byte
}
