// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type Watch struct {
	ID          int64
	Name        string
	Url         string
	LastFetch   sql.NullTime
	LastContent []byte
}
